[package]
name = "mcumgrctl-eth"
description = "mcumgrctl with the raw Ethernet (L2) backend"
categories = ["command-line-utilities"]

version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
readme = "../README.md"
keywords.workspace = true

[features]
# Also include mcumgrctl's BLE backend (needs D-Bus on Linux)
ble = ["mcumgrctl/ble"]

# Build libdbus from source instead of linking to the system library
vendored-dbus = ["mcumgrctl/vendored-dbus"]

[dependencies]
mcumgrctl.workspace = true
mcumgr-transport-ethernet = { workspace = true, features = ["cli"] }
miette.workspace = true
